export JULIA_DEPOT_PATH=$JULIA_DEPOT_PATH_BACKUP
export JULIA_PROJECT=$JULIA_PROJECT_BACKUP
export JULIA_LOAD_PATH=$JULIA_LOAD_PATH_BACKUP
export JULIA_SSL_CA_ROOTS_PATH=$JULIA_SSL_CA_ROOTS_PATH_BACKUP

unset JULIA_DEPOT_PATH_BACKUP
unset JULIA_PROJECT_BACKUP
unset JULIA_LOAD_PATH_BACKUP
unset JULIA_SSL_CA_ROOTS_PATH_BACKUP

if [ -z $JULIA_DEPOT_PATH ]; then
    unset JULIA_DEPOT_PATH
fi
if [ -z $JULIA_PROJECT ]; then
    unset JULIA_PROJECT
fi
if [ -z $JULIA_LOAD_PATH ]; then
    unset JULIA_LOAD_PATH
fi
if [ -z $JULIA_SSL_CA_ROOTS_PATH ]; then
    unset JULIA_SSL_CA_ROOTS_PATH
fi
