{% set name = "julia" %}
{% set version = "1.7.2" %}
{% set sha256 = "c1b4f1f75aac34c40e81805cba2d87f1e72f9ce1405a525273c3688eee12366f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: julia-{{ version }}-full.tar.gz
  url: https://github.com/JuliaLang/julia/releases/download/v{{ version }}/julia-{{ version }}-full.tar.gz
  sha256: {{ sha256 }}
  patches:
    ## from https://github.com/archlinux/svntogit-community/tree/packages/julia/trunk
    - patches/julia-hardcoded-libs.patch
    ## see: https://github.com/JuliaLang/julia/issues/43249#issuecomment-981147025
    ## and: https://github.com/archlinux/svntogit-community/blob/packages/julia/trunk/julia-libgit-1.2.patch
    - patches/libgit2-patch.diff  # [linux]
    ## issues with this precompile test, see https://github.com/JuliaLang/julia/issues/43535
    - patches/0002-disable-testing-Baz.baz-1.patch  # [linux]
    ## fix the curl issues:
    ## see: https://github.com/JuliaLang/Downloads.jl/issues/172
    - patches/0001-upgrading-downloads-v1.7.1.patch

build:
  skip: true  # [win]
  number: 0
  features:

requirements:
  build:
    - make
    - perl
    - python 3
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openblas-ilp64  # [x86]
    - patchelf  # [linux]
    - openlibm <0.8.0
    - gmp
    - mpfr
    - curl
    - libgit2  # [not osx]
    - libssh2
    - libosxunwind  # [osx]
    - libunwind  # [linux]
    - mbedtls  # [not osx]
    - arpack
    - suitesparse
    - pcre2
    - git
    - libutf8proc
    - libnghttp2
    - zlib
    - p7zip

  run:
    - openblas-ilp64  # [x86]
    - libosxunwind  # [osx]
    - libunwind  # [linux]
    - gmp
    - mpfr
    - openlibm <0.8.0
    - arpack
    - suitesparse
    - pcre2
    - curl
    - libgit2  # [not osx]
    - libssh2
    - mbedtls  # [not osx]
    - git
    - libutf8proc
    - libnghttp2
    - zlib
    - p7zip

test:
  commands:
    # check out versioninfo
    - julia -e 'using InteractiveUtils; InteractiveUtils.versioninfo()'
    # see if env vars are defined correctly
    - echo $CONDA_JL_HOME
    - echo $CONDA_JL_CONDA_EXE
    # run julia tests
    - julia -e 'Base.runtests(["subarray", "core", "compiler", "worlds", "keywordargs", "numbers", "subtype", "char", "strings", "triplequote", "unicode", "intrinsics", "dict", "hashing", "iobuffer", "staged", "offsetarray", "arrayops", "tuple", "reduce", "reducedim", "abstractarray", "intfuncs", "simdloop", "vecelement",
      "rational", "bitarray", "copy", "math", "fastmath", "functional", "iterators", "operators", "ordering", "path", "ccall", "parse", "gmp", "sorting", "spawn", "backtrace", "exceptions", "file", "read", "version", "namedtuple", "mpfr", "broadcast", "complex", "floatapprox", "reflection", "regex", "float16", "combinatorics",
      "sysinfo", "env", "rounding", "ranges", "mod2pi", "euler", "show", "client", "errorshow", "sets", "goto", "llvmcall", "llvmcall2", "ryu", "some", "meta", "stacktraces", "docs", "misc", "threads", "stress", "binaryplatforms", "atexit", "enums", "int", "interpreter", "checked", "bitset", "floatfuncs",
      "precompile", "boundscheck", "error", "ambiguous", "cartesian", "osutils", "channels", "iostream", "secretbuffer", "specificity", "reinterpretarray", "syntax", "corelogging", "missing", "asyncmap", "smallarrayshrink", "download", "opaque_closure", "filesystem"]; ncores=ceil(Int, Sys.CPU_THREADS))'  # all except stdlib?
    - julia --project -e 'delete!(ENV, "JULIA_PROJECT"); delete!(ENV, "JULIA_LOAD_PATH"); Base.runtests(["loading", "cmdlineargs"])' # Julia 1.7.1 tests error here when a project is defined
    - julia -e 'import Pkg;Pkg.add("LibSSH2_jll")'
    - julia -e 'import Pkg;Pkg.add("Sundials")'
  requires:
    - perl

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science
  description: |
     Julia is a high-level, high-performance dynamic language for technical computing.
     The main homepage for Julia can be found at julialang.org.
  dev_url: https://github.com/JuliaLang/julia
  doc_url: https://docs.julialang.org

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bgruening
    - dfornika
    - acaprez
    - mariusvniekerk
    - abhi18av
    - mkitti
    - ngam
