{% set name = "julia" %}
{% set version = "0.6.0" %}
{% set sha256 = "1c62bfce8075acf2b5b02355520a61210690324eceb021030681459d18a3a665" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/JuliaLang/julia/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [osx or win]
  number: 0
  features:
    - blas_{{ variant }}

requirements:
  build:
    - gcc  # [linux]
    - llvm  # [osx]
    - toolchain
    - patchelf
    - cmake
    - zlib 1.2.8
    - python 2.7.*
    - perl 5.20.*
    - openblas 0.2.19|0.2.19.*
    - blas 1.1 {{ variant }}
    - fftw
    - gmp 6.1.*
    - mpfr 3.1.*
    - curl
    - libgit2
    - arpack
    - suitesparse
    
  run:
    - zlib 1.2.8
    - libgcc  # [linux]
    - libgit2
    - fftw
    - gmp 6.1.*
    - mpfr 3.1.*
    - openblas 0.2.19|0.2.19.*
    - blas 1.1 {{ variant }}
    - arpack
    - suitesparse
    - curl

test:
  commands:
    - julia -e 'Base.runtests("all"); Base.runtests("pkg libgit2-online")'
  requires:
    - perl

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science

extra:
  recipe-maintainers:
    - bgruening
    - dfornika
    - acaprez
