{% set name = "julia" %}
{% set version = "0.6.0" %}
{% set sha256 = "2b3f1299333c8e2c6949f093e6168cc4c71c8cdf75e9ed7eccb84752d76dd8fb" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/JuliaLang/julia/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [win]
  number: 200
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - patchelf  # [linux]
    - cmake
    - zlib 1.2.8
    - python 2.7.*
    - perl 5.20.*
    - openblas 0.2.19|0.2.19.*
    - openlibm 0.5.4
    - openspecfun 0.5.3
    - blas 1.1 {{ variant }}
    - fftw
    - gmp 6.1.*
    - mpfr 3.1.*
    - curl
    - libgit2
    - arpack
    - suitesparse
    - pcre2 10.21
    
  run:
    - zlib 1.2.8
    - libgit2
    - fftw
    - gmp 6.1.*
    - mpfr 3.1.*
    - openblas 0.2.19|0.2.19.*
    - openlibm 0.5.4
    - openspecfun 0.5.3
    - blas 1.1 {{ variant }}
    - arpack
    - suitesparse
    - curl
    - pcre2 10.21

test:
  commands:
    - julia -e 'Base.runtests("all"); Base.runtests("pkg libgit2-online")'
  requires:
    - perl

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science

extra:
  recipe-maintainers:
    - bgruening
    - dfornika
    - acaprez
    - abhi18av
