{% set name = "julia" %}
{% set version = "1.0.4" %}
{% set sha256 = "39e455331e1b293e20bb9ccc5d731d9e82b63f6d6610811e86186431aaaac15b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/JuliaLang/julia/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [win]
  number: 0
  features:

requirements:
  build:
    - cmake-binary
    - perl
    - python 2.7.*
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - patchelf  # [linux]
    - zlib
    - openlibm 0.5.4
    - openspecfun 0.5.3
    - fftw
    - gmp
    - mpfr
    - curl
    - libgit2 0.27
    - libosxunwind  # [osx]
    - arpack
    - suitesparse
    - pcre2 10.23

  run:
    - zlib
    - {{ pin_compatible("libgit2", max_pin="x.x") }}
    - libosxunwind  # [osx]
    - fftw
    - gmp
    - mpfr
    - openlibm 0.5.4
    - openspecfun 0.5.3
    - arpack
    - suitesparse
    - curl
    - pcre2 10.23

test:
  commands:
    - julia -e 'Base.runtests("LibGit2/online Pkg/pkg")'
  requires:
    - perl

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bgruening
    - dfornika
    - acaprez
    - mariusvniekerk
    - abhi18av
