{% set name = "julia" %}
{% set version = "1.5.0" %}
{% set sha256 = "cd5e03ff9d8572a4b236bddca97d2692305dc3145a479245002eda130bb2d8cd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/JuliaLang/julia/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [win]
  number: 5
  features:

requirements:
  build:
    - cmake-binary
    - perl
    - python
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - patchelf  # [linux]
    - zlib
    - openlibm
    - openspecfun
    - fftw
    - gmp
    - mpfr
    - curl
    - libgit2 0.28.*
    - arpack
    - suitesparse
    - pcre2

  run:
    - zlib
    - {{ pin_compatible("libgit2", max_pin="x.x") }}
    - fftw
    - gmp
    - mpfr
    - openlibm
    - openspecfun
    - arpack
    - suitesparse
    - curl
    - pcre2

test:
  commands:
    - touch /home/conda/.gitconfig   # [linux and CI == "azure"]
    - git config --global user.name "John Doe"
    - git config --global user.email johndoe@example.com
    - julia -e 'Base.runtests("LibGit2/online Pkg/pkg")'
  requires:
    - perl
    - git

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bgruening
    - dfornika
    - acaprez
    - mariusvniekerk
    - abhi18av
