{% set name = "julia" %}
{% set version = "1.6.4" %}
{% set sha256 = "954578b973fdb891c88fa1eedd931129e215ab928ecc416dd0bdf6c70549d2fc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: julia-{{ version }}-full.tar.gz
  url: https://github.com/JuliaLang/julia/releases/download/v{{ version }}/julia-{{ version }}-full.tar.gz
  sha256: {{ sha256 }}
  patches:
    ## from https://github.com/archlinux/svntogit-community/tree/packages/julia/trunk
    - julia-hardcoded-libs.patch

build:
  skip: true  # [win]
  number: 2
  features:

requirements:
  build:
    - perl
    - python 3
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openblas-ilp64
    - patchelf  # [linux]
    - openlibm
    - gmp
    - mpfr
    - curl
    - libgit2  # [not osx]
    - libssh2
    - libosxunwind  # [osx]
    - libunwind  # [linux]
    - mbedtls  # [not osx]
    - arpack
    - suitesparse
    - pcre2
    - git
    - libutf8proc
    - libnghttp2
    - zlib
    - p7zip

  run:
    - openblas-ilp64
    - libosxunwind  # [osx]
    - libunwind  # [linux]
    - gmp
    - mpfr
    - openlibm
    - arpack
    - suitesparse
    - pcre2
    - curl
    - libgit2  # [not osx]
    - libssh2
    - mbedtls  # [not osx]
    - git
    - libutf8proc
    - libnghttp2
    - zlib
    - p7zip

test:
  commands:
    - julia -e 'Base.runtests(["subarray", "core", "compiler", "worlds", "keywordargs", "numbers", "subtype", "char", "strings", "triplequote", "unicode", "intrinsics", "dict", "hashing", "iobuffer", "staged", "offsetarray", "arrayops", "tuple", "reduce", "reducedim", "abstractarray", "intfuncs", "simdloop", "vecelement",
      "rational", "bitarray", "copy", "fastmath", "functional", "iterators", "operators", "ordering", "path", "ccall", "parse", "loading", "gmp", "sorting", "spawn", "backtrace", "exceptions", "file", "read", "version", "namedtuple", "mpfr", "broadcast", "complex", "floatapprox", "reflection", "regex", "float16", "combinatorics",
      "sysinfo", "env", "rounding", "ranges", "mod2pi", "euler", "show", "client", "errorshow", "sets", "goto", "llvmcall", "llvmcall2", "ryu", "some", "meta", "stacktraces", "docs", "misc", "threads", "stress", "binaryplatforms", "atexit", "enums", "cmdlineargs", "int", "interpreter", "checked", "bitset", "floatfuncs",
      "precompile", "boundscheck", "error", "ambiguous", "cartesian", "osutils", "channels", "iostream", "secretbuffer", "specificity", "reinterpretarray", "syntax", "corelogging", "missing", "asyncmap", "smallarrayshrink", "download"])' # all except stdlib, add "opaque_closure", "filesystem" with 1.7
    - julia -e 'Base.runtests(["math"])'  # [not osx] due to failure on math.jl:296, pre-haswell processor
    - julia -e 'import Pkg;Pkg.add("LibSSH2_jll")'
    - julia -e 'import Pkg;Pkg.add("Sundials")'
  requires:
    - perl

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bgruening
    - dfornika
    - acaprez
    - mariusvniekerk
    - abhi18av
    - mkitti
