{% set name = "julia" %}
{% set buildnum_jl = "132" %}
{% set version = "1.9.0.dev." ~ buildnum_jl %}
{% set git_rev = "fb4118a37b8ebb199962629ac54471ce6e19be9e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/JuliaLang/julia.git
  git_rev: {{ git_rev }}
  ## Increase if the build number gets close to this value
  git_depth: 2000
  patches:
    ## from https://github.com/archlinux/svntogit-community/tree/packages/julia/trunk
    - patches/julia-hardcoded-libs.patch
    ## issues with this precompile test, see https://github.com/JuliaLang/julia/issues/43535
    - patches/0002-disable-testing-Baz.baz-1.patch  # [linux]

build:
  skip: true  # [win]
  number: 0
  features:

requirements:
  build:
    - make
    - perl
    - python 3
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openblas-ilp64
    - patchelf  # [linux]
    - openlibm
    - gmp
    - mpfr
    - curl
    - libgit2  # [not osx]
    - libssh2
    - libosxunwind  # [osx]
    - libunwind  # [linux]
    - mbedtls  # [not osx]
    - arpack
    - suitesparse
    - pcre2
    - git
    - libutf8proc
    - libnghttp2
    - zlib
    - p7zip

  run:
    - openblas-ilp64
    - libosxunwind  # [osx]
    - libunwind  # [linux]
    - gmp
    - mpfr
    - openlibm
    - arpack
    - suitesparse
    - pcre2
    - curl
    - libgit2  # [not osx]
    - libssh2
    - mbedtls  # [not osx]
    - git
    - libutf8proc
    - libnghttp2
    - zlib
    - p7zip

test:
  commands:
    # check out versioninfo
    - julia -e 'using InteractiveUtils; InteractiveUtils.versioninfo()'
    # see if env vars are defined correctly
    - echo $CONDA_JL_HOME
    - echo $CONDA_JL_CONDA_EXE
    # run julia tests
    - julia -e 'Base.runtests(["subarray", "core", "compiler", "worlds", "keywordargs", "numbers", "subtype", "char", "strings", "triplequote", "unicode", "intrinsics", "dict", "hashing", "iobuffer", "staged", "offsetarray", "arrayops", "tuple", "reduce", "reducedim", "abstractarray", "intfuncs", "simdloop", "vecelement",
      "rational", "bitarray", "copy", "math", "fastmath", "functional", "iterators", "operators", "ordering", "path", "ccall", "parse", "gmp", "sorting", "spawn", "backtrace", "exceptions", "file", "read", "version", "namedtuple", "mpfr", "broadcast", "complex", "floatapprox", "reflection", "regex", "float16", "combinatorics",
      "sysinfo", "env", "rounding", "ranges", "mod2pi", "euler", "show", "client", "errorshow", "sets", "goto", "llvmcall", "llvmcall2", "ryu", "some", "meta", "stacktraces", "docs", "misc", "threads", "stress", "binaryplatforms", "atexit", "enums", "int", "interpreter", "checked", "bitset", "floatfuncs",
      "precompile", "boundscheck", "error", "ambiguous", "cartesian", "osutils", "channels", "iostream", "secretbuffer", "specificity", "reinterpretarray", "syntax", "corelogging", "missing", "asyncmap", "smallarrayshrink", "download", "opaque_closure", "filesystem"]; ncores=ceil(Int, Sys.CPU_THREADS))'  # all except stdlib?
    - julia --project -e 'Base.runtests(["loading"])' # Julia 1.7.1 tests error here when a project is defined
    # splitting cmdlineargs as it is stuck... 
    - julia --project -e 'Base.runtests(["cmdlineargs"])' # Julia 1.7.1 tests error here when a project is defined
    - julia -e 'import Pkg;Pkg.add("LibSSH2_jll")'
    - julia -e 'import Pkg;Pkg.add("Sundials")'
    #- julia -e 'import PKg;Pkg.add("Conda"); using Conda; ENV["CONDA_EXE"] == Conda.conda && isfile(Conda.conda) ? exit(0) : exit(1)'
  requires:
    - perl

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science
  description: |
     Julia is a high-level, high-performance dynamic language for technical computing.
     The main homepage for Julia can be found at julialang.org.
  dev_url: https://github.com/JuliaLang/julia
  doc_url: https://docs.julialang.org

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bgruening
    - dfornika
    - acaprez
    - mariusvniekerk
    - abhi18av
    - mkitti
    - ngam
