{% set name = "julia" %}
{% set version = "1.4.2" %}
{% set sha256 = "21a242a5f63db6e25e808e9662416b62004f39b111b3afb751efd760bcc34dc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/JuliaLang/julia/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [win]
  number: 0
  features:

# Fix versions based on https://github.com/JuliaLang/julia/blob/v1.4.2/deps/Versions.make

requirements:
  build:
    - cmake-binary
    - perl
    - python 2.7.*
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - llvm-openmp 8.0.1
    - pcre2 10.31
    - dsfmt 2.2.3
    - openblas  # 0.3.5
    - liblapack  # 3.5.0
    - suitesparse 5.4.0
    - openlibm 0.6.0
    - libunwind 1.3.1  # [linux]
    - libosxunwind 0.0.5  # [osx]
    - gmp 6.1.2
    - mpfr 4.0.2
    - patchelf 0.9  # [linux]
    # - mbedtls  # not available on conda 
    - libssh2 1.9.0
    - curl   # 7.66.0
    - libgit2 1.1.0
    - libuv 1.29.1
    - objconv 2.49
    - zlib 1.2.11

  run:
    - llvm-openmp 8.0.1
    - pcre2 10.31
    - dsfmt 2.2.3
    # - openblas  # 0.3.5
    # - liblapack  # 3.5.0
    - suitesparse 5.4.0
    - openlibm 0.6.0
    - libunwind 1.3.1  # [linux]
    - libosxunwind 0.0.5  # [osx]
    - gmp 6.1.2
    - mpfr 4.0.2
    - patchelf 0.9  # [linux]
    # - mbedtls  # not available on conda 
    - libssh2 1.9.0
    - curl  # 7.66.0
    - libgit2 1.1.0
    - libuv 1.29.1
    - objconv 2.49
    - zlib 1.2.11

test:
  commands:
    - julia -e 'Base.runtests("LibGit2/online Pkg/pkg")'
  requires:
    - perl

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bgruening
    - dfornika
    - acaprez
    - mariusvniekerk
    - abhi18av
