{% set name = "julia" %}
{% set version = "0.6.1" %}
{% set sha256 = "d4910837c0f7b43e18ebe62c6b99edcfa20611e0a98a95777065a4a3112544ef" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/JuliaLang/julia/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [osx or win]
  number: 203
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake
    - perl
    - python 2.7.*
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - patchelf  # [linux]
    - zlib
    - openblas
    - openlibm 0.5.4
    - openspecfun 0.5.3
    - blas 1.1 {{ variant }}
    - fftw
    - gmp
    - mpfr
    - curl
    - libgit2
    - arpack
    - suitesparse
    - pcre2 10.23

  run:
    - zlib
    - libgit2
    - fftw
    - gmp
    - mpfr
    - openblas
    - openlibm 0.5.4
    - openspecfun 0.5.3
    - blas 1.1 {{ variant }}
    - arpack
    - suitesparse
    - curl
    - pcre2 10.23

test:
  commands:
    - julia -e 'Base.runtests("pkg libgit2-online")'
  requires:
    - perl

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science

extra:
  recipe-maintainers:
    - bgruening
    - dfornika
    - acaprez
