azure:
  store_build_artifacts: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
conda_build:
  pkg_format: '2'
remote_ci_setup:
  - conda-forge-ci-setup=3
  - py-lief<0.12
  - patchelf=0.17.0