travis:
  secure:
    BINSTAR_TOKEN: BJThkirAjjJRL0ySaDEG2h/W4TwHsOSZVT5nkAyqmXHxVMeYSKDb4G5nTk4LohMQ2Rypf+tgqye1GOoFgjIYRsK1KUV0E1m8W2MdZG+t958s0Q48jbdQGeacRjuif73r60F0/yYxaLS2XrggPzj1eZnDO8zYHpzYqEZ04HGmqU9O9LW7mmcD04ezcdkmLlrkFn/j+Txwi4fBryhi4qOnr0FSk9Q+su9VFc6kwlCtsCT83+od77dLZEA0gW1aLz2pkIVHg/Mu+yK1nq9Y0j6EAm9Pos50broOpfrN4wjag5+w+xdf9zmtlhZV7mgj1/fDMJdt5xsWdPBQAodlyO+iy4bpAGl322uEy9CHVBlaAL3U8pzeG4W7Z9+VdrWEzs3XjQMXxttAFiLulk64Dvi6DARvSwug4NQlgZSpeh84w7VflSMzzx4gyjodDJUfHnjk5h+qPBvkrz/o2piEtjux5LcdBd1s2RaUFFkoZJYAZS5ssvY9DttEb/ATpk/c14NsL1iLFi4ROwcOro+/yjL12xVxBzYkRI+hNfQW1bpBm0bF0UyheIFVll6sdwPihCcCrXceEXC4XIOoKtG/7aufAH+rQpVj7SH+im4PF6G20FsN1t3m6ym5naykViPGnRwOfvUlCdgUBV+aBdZKRU+79GPXkIOpv+Yaip9xrfK4IPQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
