jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 240
  strategy:
    maxParallel: 8
    matrix:
      linux_c_compilergcccxx_compilergxxfortran_compilergfortran:
        CONFIG: linux_c_compilergcccxx_compilergxxfortran_compilergfortran
      linux_c_compilertoolchain_ccxx_compilertoolchain_cxxfortran_compilertoolchain_fort:
        CONFIG: linux_c_compilertoolchain_ccxx_compilertoolchain_cxxfortran_compilertoolchain_fort
  steps:
  - script: |
      sudo pip install --upgrade pip
      sudo pip install setuptools shyaml
    displayName: Install dependencies

  - script: .azure-pipelines/run_docker_build.sh
    displayName: Run docker build